// Firebase-backed AuthService implementation.
// Replaces the simulated stub. Uses FirebaseAuth, GoogleSignIn and Firestore.
// Requires firebase_options.dart generated by FlutterFire CLI.
/*
import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';

class CheckResult {
  final bool exists;
  final List<String> providers;
  final String status;
  CheckResult({required this.exists, this.providers = const <String>[], this.status = 'none'});
}

class GoogleSignInResult {
  final bool newUser;
  final String? uid;
  final String? displayName;
  GoogleSignInResult({required this.newUser, this.uid, this.displayName});
}

class VerifyResult {
  final bool success;
  final bool newUser;
  final String? uid;
  VerifyResult({required this.success, required this.newUser, this.uid});
}

class AuthService {
  static final FirebaseAuth _auth = FirebaseAuth.instance;
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static final GoogleSignIn _googleSignIn = GoogleSignIn();

  /// Checks identifier existence.
  /// method: 'email' or 'phone'
  /// This function first queries Firestore for a user doc (preferred).
  /// If no user doc found for an email, it attempts to query FirebaseAuth
  /// for sign-in methods using a dynamic call to avoid compile-time SDK mismatches.
  static Future<CheckResult> checkIdentifier({required String method, required String identifier}) async {
    try {
      if (method == 'email') {
        // 1) Query Firestore users collection by email
        final q = await _firestore.collection('users').where('email', isEqualTo: identifier).limit(1).get();
        final existsInFirestore = q.docs.isNotEmpty;
        if (existsInFirestore) {
          final data = q.docs.first.data();
          final provider = (data['provider'] is String && (data['provider'] as String).isNotEmpty) ? data['provider'] as String : 'password';
          final status = data['status'] ?? 'active';
          return CheckResult(exists: true, providers: <String>[provider], status: status);
        }

        // 2) If not found in Firestore, try FirebaseAuth.fetchSignInMethodsForEmail.
        // Use dynamic invocation to avoid compile-time errors on different firebase_auth versions.
        try {
          final dynamic authDynamic = _auth;
          final methodsDynamic = await authDynamic.fetchSignInMethodsForEmail(identifier);
          if (methodsDynamic != null) {
            final List methodsList = List.from(methodsDynamic as Iterable);
            if (methodsList.isNotEmpty) {
              final providers = methodsList.map((e) => e.toString()).toList();
              return CheckResult(exists: true, providers: providers, status: 'active');
            }
          }
        } catch (e) {
          // If the method isn't available or the call fails, fall through and treat as not found.
          // This avoids crashing on SDK mismatches.
        }

        // Not found anywhere
        return CheckResult(exists: false, providers: const <String>[], status: 'none');
      } else if (method == 'phone') {
        // Check Firestore users collection for phone field
        final q = await _firestore.collection('users').where('phone', isEqualTo: identifier).limit(1).get();
        final exists = q.docs.isNotEmpty;
        if (exists) {
          final data = q.docs.first.data();
          final provider = (data['provider'] is String && (data['provider'] as String).isNotEmpty) ? data['provider'] as String : 'phone';
          final status = data['status'] ?? 'active';
          return CheckResult(exists: true, providers: <String>[provider], status: status);
        } else {
          return CheckResult(exists: false, providers: const <String>[], status: 'none');
        }
      } else {
        return CheckResult(exists: false, providers: const <String>[], status: 'none');
      }
    } catch (e) {
      // On any error, return a safe default
      return CheckResult(exists: false, providers: const <String>[], status: 'none');
    }
  }

  /// Initiates phone number verification using Firebase SMS flow.
  /// Returns a map containing verificationId and newUser flag.
  /// Caller should navigate to OTP screen and pass verificationId.
  static Future<Map<String, dynamic>> sendPhoneVerification({required String phone}) async {
    // Determine if user exists
    final q = await _firestore.collection('users').where('phone', isEqualTo: phone).limit(1).get();
    final isNew = q.docs.isEmpty;

    final completer = Completer<Map<String, dynamic>>();

    await _auth.verifyPhoneNumber(
      phoneNumber: phone,
      timeout: const Duration(minutes: 2),
      verificationCompleted: (PhoneAuthCredential credential) async {
        // Auto-retrieval or instant verification.
        try {
          final userCredential = await _auth.signInWithCredential(credential);
          final uid = userCredential.user?.uid;
          if (userCredential.additionalUserInfo?.isNewUser ?? false) {
            // mark as new user; do not create full profile until role selection
          }
          if (!completer.isCompleted) {
            completer.complete({'verificationId': '', 'auto': true, 'uid': uid, 'newUser': isNew});
          }
        } catch (e) {
          if (!completer.isCompleted) {
            completer.completeError(e);
          }
        }
      },
      verificationFailed: (FirebaseAuthException e) {
        if (!completer.isCompleted) completer.completeError(e);
      },
      codeSent: (String verificationId, int? resendToken) {
        if (!completer.isCompleted) {
          completer.complete({'verificationId': verificationId, 'auto': false, 'newUser': isNew});
        }
      },
      codeAutoRetrievalTimeout: (String verificationId) {
        // timeout; verificationId may still be used for manual code entry
      },
    );

    return completer.future;
  }

  /// Verifies phone OTP using verificationId and smsCode.
  /// Signs in or creates the user. If newUser true, caller should call completeSignup() to set profile and role.
  static Future<VerifyResult> verifyPhoneOtp({required String verificationId, required String smsCode}) async {
    try {
      final credential = PhoneAuthProvider.credential(verificationId: verificationId, smsCode: smsCode);
      final userCredential = await _auth.signInWithCredential(credential);
      final uid = userCredential.user?.uid;
      final isNew = userCredential.additionalUserInfo?.isNewUser ?? false;
      // If sign-in succeeded but user doc missing, leave creation to completeSignup
      return VerifyResult(success: true, newUser: isNew, uid: uid);
    } on FirebaseAuthException {
      return VerifyResult(success: false, newUser: false, uid: null);
    } catch (e) {
      return VerifyResult(success: false, newUser: false, uid: null);
    }
  }

  /// Email/password sign-in. Returns a map with success, uid, role, status.
  static Future<Map<String, dynamic>> signInWithEmail({required String email, required String password}) async {
    try {
      final uc = await _auth.signInWithEmailAndPassword(email: email, password: password);
      final uid = uc.user?.uid;
      if (uid == null) return {'success': false};
      final doc = await _firestore.collection('users').doc(uid).get();
      if (!doc.exists) {
        // user exists in auth but no profile - treat as new user needing profile
        return {'success': true, 'uid': uid, 'newProfile': true};
      }
      final data = doc.data()!;
      return {'success': true, 'uid': uid, 'role': data['role'], 'status': data['status'] ?? 'active'};
    } on FirebaseAuthException catch (e) {
      return {'success': false, 'error': e.code};
    } catch (e) {
      return {'success': false, 'error': e.toString()};
    }
  }

  /// Create user with email/password and set initial user doc in Firestore.
  /// Admin accounts are created active (no approval required).
  static Future<Map<String, dynamic>> signUpWithEmail({required String displayName, required String email, required String password, required String role}) async {
    try {
      final uc = await _auth.createUserWithEmailAndPassword(email: email, password: password);
      final uid = uc.user?.uid;
      if (uid == null) return {'success': false};
      // Update display name
      await uc.user?.updateDisplayName(displayName);
      // Immediately activate all roles (admin is active too)
      final status = 'active';
      final docData = {
        'displayName': displayName,
        'email': email,
        'phone': null,
        'role': role,
        'status': status,
        'provider': 'password',
        'createdAt': FieldValue.serverTimestamp(),
      };
      await _firestore.collection('users').doc(uid).set(docData);
      return {'success': true, 'uid': uid, 'role': role, 'status': status};
    } on FirebaseAuthException catch (e) {
      return {'success': false, 'error': e.code};
    } catch (e) {
      return {'success': false, 'error': e.toString()};
    }
  }

  /// Google Sign-In and Firebase auth. If new user, caller should call completeSignup to write role.
  static Future<GoogleSignInResult> signInWithGoogle() async {
    try {
      final googleUser = await _googleSignIn.signIn();
      if (googleUser == null) {
        return GoogleSignInResult(newUser: false, uid: null, displayName: null);
      }
      final googleAuth = await googleUser.authentication;
      final credential = GoogleAuthProvider.credential(accessToken: googleAuth.accessToken, idToken: googleAuth.idToken);
      final userCredential = await _auth.signInWithCredential(credential);
      final uid = userCredential.user?.uid;
      final isNew = userCredential.additionalUserInfo?.isNewUser ?? false;
      final displayName = userCredential.user?.displayName;
      // If new: do not create full profile until role selected; caller should call completeSignup(uid,...)
      return GoogleSignInResult(newUser: isNew, uid: uid, displayName: displayName);
    } catch (e) {
      rethrow;
    }
  }

  /// Finalize signup for new users (social or phone). Creates /users/{uid} document with chosen role.
  /// Admin accounts are created active (no approval required).
  static Future<bool> completeSignup({required String uid, required String displayName, required String role, String? email, String? phone, String provider = 'unknown'}) async {
    try {
      // Immediately activate all roles (admin included)
      final status = 'active';
      final docData = {
        'displayName': displayName,
        'email': email,
        'phone': phone,
        'role': role,
        'status': status,
        'provider': provider,
        'createdAt': FieldValue.serverTimestamp(),
      };
      await _firestore.collection('users').doc(uid).set(docData, SetOptions(merge: true));
      // update Firebase user displayName if possible
      final user = _auth.currentUser;
      if (user != null && (user.displayName == null || user.displayName!.isEmpty)) {
        await user.updateDisplayName(displayName);
      }
      return true;
    } catch (e) {
      return false;
    }
  }

  static Future<void> signOut() async {
    try {
      await _auth.signOut();
      await _googleSignIn.signOut();
    } catch (_) {}
  }
}

 */
/*
// lib/services/auth_service.dart


import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';

class CheckResult {
  final bool exists;
  final List<String> providers;
  final String status;
  CheckResult({required this.exists, this.providers = const <String>[], this.status = 'none'});
}

class GoogleSignInResult {
  final bool newUser;
  final String? uid;
  final String? displayName;
  GoogleSignInResult({required this.newUser, this.uid, this.displayName});
}

class VerifyResult {
  final bool success;
  final bool newUser;
  final String? uid;
  VerifyResult({required this.success, required this.newUser, this.uid});
}

class AuthService {
  static final FirebaseAuth _auth = FirebaseAuth.instance;
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static final GoogleSignIn _googleSignIn = GoogleSignIn();

  static Future<CheckResult> checkIdentifier({required String method, required String identifier}) async {
    try {
      if (method == 'email') {
        final q = await _firestore.collection('users').where('email', isEqualTo: identifier).limit(1).get();
        final existsInFirestore = q.docs.isNotEmpty;
        if (existsInFirestore) {
          final data = q.docs.first.data();
          final provider = (data['provider'] is String && (data['provider'] as String).isNotEmpty)
              ? data['provider'] as String
              : 'password';
          final status = data['status'] ?? 'active';
          return CheckResult(exists: true, providers: <String>[provider], status: status);
        }

        try {
          final dynamic authDynamic = _auth;
          final methodsDynamic = await authDynamic.fetchSignInMethodsForEmail(identifier);
          if (methodsDynamic != null) {
            final List methodsList = List.from(methodsDynamic as Iterable);
            if (methodsList.isNotEmpty) {
              final providers = methodsList.map((e) => e.toString()).toList();
              return CheckResult(exists: true, providers: providers, status: 'active');
            }
          }
        } catch (e) {}
        return CheckResult(exists: false);
      } else if (method == 'phone') {
        final q = await _firestore.collection('users').where('phone', isEqualTo: identifier).limit(1).get();
        final exists = q.docs.isNotEmpty;
        if (exists) {
          final data = q.docs.first.data();
          final provider = (data['provider'] is String && (data['provider'] as String).isNotEmpty)
              ? data['provider'] as String
              : 'phone';
          final status = data['status'] ?? 'active';
          return CheckResult(exists: true, providers: <String>[provider], status: status);
        } else {
          return CheckResult(exists: false);
        }
      } else {
        return CheckResult(exists: false);
      }
    } catch (e) {
      return CheckResult(exists: false);
    }
  }

  static Future<Map<String, dynamic>> sendPhoneVerification({required String phone}) async {
    final q = await _firestore.collection('users').where('phone', isEqualTo: phone).limit(1).get();
    final isNew = q.docs.isEmpty;

    final completer = Completer<Map<String, dynamic>>();

    await _auth.verifyPhoneNumber(
      phoneNumber: phone,
      timeout: const Duration(minutes: 2),
      verificationCompleted: (PhoneAuthCredential credential) async {
        try {
          final userCredential = await _auth.signInWithCredential(credential);
          final uid = userCredential.user?.uid;
          if (!completer.isCompleted) {
            completer.complete({'verificationId': '', 'auto': true, 'uid': uid, 'newUser': isNew});
          }
        } catch (e) {
          if (!completer.isCompleted) completer.completeError(e);
        }
      },
      verificationFailed: (FirebaseAuthException e) {
        if (!completer.isCompleted) completer.completeError(e);
      },
      codeSent: (String verificationId, int? resendToken) {
        if (!completer.isCompleted) {
          completer.complete({'verificationId': verificationId, 'auto': false, 'newUser': isNew});
        }
      },
      codeAutoRetrievalTimeout: (_) {},
    );

    return completer.future;
  }

  static Future<VerifyResult> verifyPhoneOtp({required String verificationId, required String smsCode}) async {
    try {
      final credential = PhoneAuthProvider.credential(verificationId: verificationId, smsCode: smsCode);
      final userCredential = await _auth.signInWithCredential(credential);
      final uid = userCredential.user?.uid;
      final isNew = userCredential.additionalUserInfo?.isNewUser ?? false;
      return VerifyResult(success: true, newUser: isNew, uid: uid);
    } on FirebaseAuthException {
      return VerifyResult(success: false, newUser: false, uid: null);
    } catch (e) {
      return VerifyResult(success: false, newUser: false, uid: null);
    }
  }

  static Future<Map<String, dynamic>> signInWithEmail({required String email, required String password}) async {
    try {
      final uc = await _auth.signInWithEmailAndPassword(email: email, password: password);
      final uid = uc.user?.uid;
      if (uid == null) return {'success': false};
      final doc = await _firestore.collection('users').doc(uid).get();
      if (!doc.exists) return {'success': true, 'uid': uid, 'newProfile': true};
      final data = doc.data()!;
      return {'success': true, 'uid': uid, 'role': data['role'], 'status': data['status'] ?? 'active'};
    } on FirebaseAuthException catch (e) {
      return {'success': false, 'error': e.code};
    } catch (e) {
      return {'success': false, 'error': e.toString()};
    }
  }

  static Future<Map<String, dynamic>> signUpWithEmail({
    required String displayName,
    required String email,
    required String password,
    required String role,
  }) async {
    try {
      final uc = await _auth.createUserWithEmailAndPassword(email: email, password: password);
      final uid = uc.user?.uid;
      if (uid == null) return {'success': false};
      await uc.user?.updateDisplayName(displayName);
      final status = 'active';
      final docData = {
        'displayName': displayName,
        'email': email,
        'phone': null,
        'role': role,
        'status': status,
        'provider': 'password',
        'createdAt': FieldValue.serverTimestamp(),
      };
      await _firestore.collection('users').doc(uid).set(docData);
      return {'success': true, 'uid': uid, 'role': role, 'status': status};
    } on FirebaseAuthException catch (e) {
      return {'success': false, 'error': e.code};
    } catch (e) {
      return {'success': false, 'error': e.toString()};
    }
  }

  static Future<GoogleSignInResult> signInWithGoogle() async {
    try {
      final googleUser = await _googleSignIn.signIn();
      if (googleUser == null) {
        return GoogleSignInResult(newUser: false, uid: null, displayName: null);
      }
      final googleAuth = await googleUser.authentication;
      final credential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );
      final userCredential = await _auth.signInWithCredential(credential);
      final uid = userCredential.user?.uid;
      final isNew = userCredential.additionalUserInfo?.isNewUser ?? false;
      final displayName = userCredential.user?.displayName;
      return GoogleSignInResult(newUser: isNew, uid: uid, displayName: displayName);
    } catch (e) {
      rethrow;
    }
  }

  static Future<bool> completeSignup({
    required String uid,
    required String displayName,
    required String role,
    String? email,
    String? phone,
    String provider = 'unknown',
  }) async {
    try {
      final status = 'active';
      final docData = {
        'displayName': displayName,
        'email': email,
        'phone': phone,
        'role': role,
        'status': status,
        'provider': provider,
        'createdAt': FieldValue.serverTimestamp(),
      };
      await _firestore.collection('users').doc(uid).set(docData, SetOptions(merge: true));
      final user = _auth.currentUser;
      if (user != null && (user.displayName == null || user.displayName!.isEmpty)) {
        await user.updateDisplayName(displayName);
      }
      return true;
    } catch (e) {
      return false;
    }
  }

  static Future<void> signOut() async {
    try {
      await _auth.signOut();
      await _googleSignIn.signOut();
    } catch (_) {}
  }
}


 */
/*

// lib/services/auth_service.dart
import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';

class CheckResult {
  final bool exists;
  final List<String> providers;
  final String status;
  CheckResult({required this.exists, this.providers = const <String>[], this.status = 'none'});
}

class GoogleSignInResult {
  final bool newUser;
  final String? uid;
  final String? displayName;
  GoogleSignInResult({required this.newUser, this.uid, this.displayName});
}

class VerifyResult {
  final bool success;
  final bool newUser;
  final String? uid;
  VerifyResult({required this.success, required this.newUser, this.uid});
}

class AuthService {
  static final FirebaseAuth _auth = FirebaseAuth.instance;
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static final GoogleSignIn _googleSignIn = GoogleSignIn();

  // ------------------ Helpers ------------------

  static Future<DocumentSnapshot?> _getUserDoc(String uid) async {
    try {
      final doc = await _firestore.collection('users').doc(uid).get();
      if (doc.exists) return doc;
    } catch (e) {
      print('AuthService._getUserDoc error: $e');
    }
    return null;
  }
/*
  static Future<String?> getUserRole(String uid) async {
    try {
      final doc = await _getUserDoc(uid);
      if (doc.exists) {
        final data = doc.data() as Map<String, dynamic>?;
        return data?["role"] as String?;
      }

    } catch (e) {
      print('AuthService.getUserRole error: $e');
    }
    return null;
  }
 */
  static Future<String?> getUserRole(String uid) async {
    try {
      final doc = await FirebaseFirestore.instance
          .collection('users')
          .doc(uid)
          .get();

      if (doc.exists) {
        final data = doc.data();
        return data?['role'] as String?;
      }
    } catch (e) {
      print('Error fetching user role: $e');
    }
    return null;
  }

  // ------------------ Identifier check ------------------
  static Future<CheckResult> checkIdentifier({required String method, required String identifier}) async {
    try {
      if (method == 'email') {
        final q = await _firestore.collection('users').where('email', isEqualTo: identifier).limit(1).get();
        if (q.docs.isNotEmpty) {
          final data = q.docs.first.data();
          final provider = (data['provider'] is String && (data['provider'] as String).isNotEmpty) ? data['provider'] as String : 'password';
          final status = data['status'] ?? 'active';
          return CheckResult(exists: true, providers: <String>[provider], status: status);
        }

        try {
          final dynamic authDynamic = _auth;
          final methodsDynamic = await authDynamic.fetchSignInMethodsForEmail(identifier);
          if (methodsDynamic != null) {
            final List methodsList = List.from(methodsDynamic as Iterable);
            if (methodsList.isNotEmpty) {
              final providers = methodsList.map((e) => e.toString()).toList();
              return CheckResult(exists: true, providers: providers, status: 'active');
            }
          }
        } catch (_) {}
        return CheckResult(exists: false);
      } else if (method == 'phone') {
        final q = await _firestore.collection('users').where('phone', isEqualTo: identifier).limit(1).get();
        final exists = q.docs.isNotEmpty;
        if (exists) {
          final data = q.docs.first.data();
          final provider = (data['provider'] is String && (data['provider'] as String).isNotEmpty) ? data['provider'] as String : 'phone';
          final status = data['status'] ?? 'active';
          return CheckResult(exists: true, providers: <String>[provider], status: status);
        }
        return CheckResult(exists: false);
      } else {
        return CheckResult(exists: false);
      }
    } catch (e) {
      print('checkIdentifier error: $e');
      return CheckResult(exists: false);
    }
  }

  // ------------------ Email sign-in / sign-up ------------------




  static Future<Map<String, dynamic>> signInWithEmail({required String email, required String password}) async {
    try {
      final uc = await _auth.signInWithEmailAndPassword(email: email, password: password);
      final uid = uc.user?.uid;
      if (uid == null) return {'success': false, 'error': 'no-uid'};
      final doc = await _firestore.collection('users').doc(uid).get();
      if (!doc.exists) return {'success': true, 'uid': uid, 'newProfile': true};
      final data = doc.data()!;
      return {'success': true, 'uid': uid, 'role': data['role'], 'status': data['status'] ?? 'active'};
    } on FirebaseAuthException catch (e) {
      return {'success': false, 'error': e.code};
    } catch (e) {
      return {'success': false, 'error': e.toString()};
    }
  }

  static Future<Map<String, dynamic>> signUpWithEmail({required String displayName, required String email, required String password, required String role}) async {
    try {
      final uc = await _auth.createUserWithEmailAndPassword(email: email, password: password);
      final uid = uc.user?.uid;
      if (uid == null) return {'success': false};
      await uc.user?.updateDisplayName(displayName);
      final status = 'active'; // you may change policy for admin to pending if required
      final docData = {
        'displayName': displayName,
        'email': email,
        'phone': null,
        'role': role,
        'status': status,
        'provider': 'password',
        'createdAt': FieldValue.serverTimestamp(),
      };
      await _firestore.collection('users').doc(uid).set(docData);
      return {'success': true, 'uid': uid, 'role': role, 'status': status};
    } on FirebaseAuthException catch (e) {
      return {'success': false, 'error': e.code};
    } catch (e) {
      return {'success': false, 'error': e.toString()};
    }
  }

  // ------------------ Phone verification (send + verify) ------------------
  static Future<Map<String, dynamic>> sendPhoneVerification({required String phone}) async {
    final q = await _firestore.collection('users').where('phone', isEqualTo: phone).limit(1).get();
    final isNew = q.docs.isEmpty;
    final completer = Completer<Map<String, dynamic>>();

    await _auth.verifyPhoneNumber(
      phoneNumber: phone,
      timeout: const Duration(seconds: 60),
      verificationCompleted: (PhoneAuthCredential credential) async {
        try {
          final userCredential = await _auth.signInWithCredential(credential);
          final uid = userCredential.user?.uid;
          if (!completer.isCompleted) completer.complete({'verificationId': '', 'auto': true, 'uid': uid, 'newUser': isNew});
        } catch (e) {
          if (!completer.isCompleted) completer.completeError(e);
        }
      },
      verificationFailed: (FirebaseAuthException e) {
        if (!completer.isCompleted) completer.completeError(e);
      },
      codeSent: (String verificationId, int? resendToken) {
        if (!completer.isCompleted) completer.complete({'verificationId': verificationId, 'auto': false, 'newUser': isNew});
      },
      codeAutoRetrievalTimeout: (String verificationId) {
        // nothing to do here
      },
    );

    return completer.future;
  }

  static Future<VerifyResult> verifyPhoneOtp({required String verificationId, required String smsCode}) async {
    try {
      final credential = PhoneAuthProvider.credential(verificationId: verificationId, smsCode: smsCode);
      final userCredential = await _auth.signInWithCredential(credential);
      final uid = userCredential.user?.uid;
      final isNew = userCredential.additionalUserInfo?.isNewUser ?? false;
      return VerifyResult(success: true, newUser: isNew, uid: uid);
    } on FirebaseAuthException catch (_) {
      return VerifyResult(success: false, newUser: false, uid: null);
    } catch (e) {
      return VerifyResult(success: false, newUser: false, uid: null);
    }
  }

  // ------------------ Google sign-in ------------------
  static Future<GoogleSignInResult> signInWithGoogle() async {
    try {
      final googleUser = await _googleSignIn.signIn();
      if (googleUser == null) {
        return GoogleSignInResult(newUser: false, uid: null, displayName: null);
      }
      final googleAuth = await googleUser.authentication;
      final credential = GoogleAuthProvider.credential(accessToken: googleAuth.accessToken, idToken: googleAuth.idToken);
      final userCredential = await _auth.signInWithCredential(credential);
      final uid = userCredential.user?.uid;
      final isNew = userCredential.additionalUserInfo?.isNewUser ?? false;
      final displayName = userCredential.user?.displayName;
      return GoogleSignInResult(newUser: isNew, uid: uid, displayName: displayName);
    } catch (e) {
      rethrow;
    }
  }

  // ------------------ Complete signup (write profile doc) ------------------
  static Future<bool> completeSignup({required String uid, required String displayName, required String role, String? email, String? phone, String provider = 'unknown'}) async {
    try {
      final status = 'active';
      final docData = {
        'displayName': displayName,
        'email': email,
        'phone': phone,
        'role': role,
        'status': status,
        'provider': provider,
        'createdAt': FieldValue.serverTimestamp(),
      };
      await _firestore.collection('users').doc(uid).set(docData, SetOptions(merge: true));
      final user = _auth.currentUser;
      if (user != null && (user.displayName == null || user.displayName!.isEmpty)) {
        await user.updateDisplayName(displayName);
      }
      return true;
    } catch (e) {
      print('completeSignup error: $e');
      return false;
    }
  }

  // ------------------ Sign out ------------------
  static Future<void> signOut() async {
    try {
      await _auth.signOut();
      await _googleSignIn.signOut();
    } catch (_) {}
  }
}

*/
/*
import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';

class CheckResult {
  final bool exists;
  final List<String> providers;
  final String status;
  CheckResult({
    required this.exists,
    this.providers = const <String>[],
    this.status = 'none',
  });
}

class GoogleSignInResult {
  final bool newUser;
  final String? uid;
  final String? displayName;
  GoogleSignInResult({
    required this.newUser,
    this.uid,
    this.displayName,
  });
}

class VerifyResult {
  final bool success;
  final bool newUser;
  final String? uid;
  VerifyResult({
    required this.success,
    required this.newUser,
    this.uid,
  });
}

class AuthService {
  static final FirebaseAuth _auth = FirebaseAuth.instance;
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static final GoogleSignIn _googleSignIn = GoogleSignIn();

  // ------------------ Get User Role ------------------
  static Future<String?> getUserRole(String uid) async {
    try {
      final doc =
      await FirebaseFirestore.instance.collection('users').doc(uid).get();
      if (doc.exists) {
        final data = doc.data();
        return data?['role'] as String?;
      }
    } catch (e) {
      print('Error fetching user role: $e');
    }
    return null;
  }

  // ------------------ Check Identifier ------------------
  static Future<CheckResult> checkIdentifier({
    required String method,
    required String identifier,
  }) async {
    try {
      if (method == 'email') {
        final q = await _firestore
            .collection('users')
            .where('email', isEqualTo: identifier)
            .limit(1)
            .get();

        if (q.docs.isNotEmpty) {
          final data = q.docs.first.data();
          final provider = (data['provider'] is String &&
              (data['provider'] as String).isNotEmpty)
              ? data['provider'] as String
              : 'password';
          final status = data['status'] ?? 'active';
          return CheckResult(
            exists: true,
            providers: <String>[provider],
            status: status,
          );
        }

        // ✅ Check using FirebaseAuth method (works with v6.1.1)
        //final List<String> methods =
        //await FirebaseAuth.instance.fetchSignInMethodsForEmail(identifier);
        final List<String> methods = await FirebaseAuth.instance
            .userManager
            .fetchSignInMethodsForEmail(identifier);

        if (methods.isNotEmpty) {
          return CheckResult(
            exists: true,
            providers: methods,
            status: 'active',
          );
        }

        return CheckResult(exists: false);
      } else if (method == 'phone') {
        final q = await _firestore
            .collection('users')
            .where('phone', isEqualTo: identifier)
            .limit(1)
            .get();
        final exists = q.docs.isNotEmpty;
        if (exists) {
          final data = q.docs.first.data();
          final provider = (data['provider'] is String &&
              (data['provider'] as String).isNotEmpty)
              ? data['provider'] as String
              : 'phone';
          final status = data['status'] ?? 'active';
          return CheckResult(
              exists: true,
              providers: <String>[provider],
              status: status);
        }
        return CheckResult(exists: false);
      } else {
        return CheckResult(exists: false);
      }
    } catch (e) {
      print('checkIdentifier error: $e');
      return CheckResult(exists: false);
    }
  }

  // ------------------ Email Login ------------------
  static Future<Map<String, dynamic>> signInWithEmail({
    required String email,
    required String password,
  }) async {
    try {
      final uc = await _auth.signInWithEmailAndPassword(
          email: email, password: password);
      final uid = uc.user?.uid;
      if (uid == null) return {'success': false, 'error': 'no-uid'};
      final doc = await _firestore.collection('users').doc(uid).get();
      if (!doc.exists) {
        return {'success': true, 'uid': uid, 'newProfile': true};
      }
      final data = doc.data()!;
      return {
        'success': true,
        'uid': uid,
        'role': data['role'],
        'status': data['status'] ?? 'active'
      };
    } on FirebaseAuthException catch (e) {
      return {'success': false, 'error': e.code};
    } catch (e) {
      return {'success': false, 'error': e.toString()};
    }
  }

  // ------------------ Email Signup ------------------
  static Future<Map<String, dynamic>> signUpWithEmail({
    required String displayName,
    required String email,
    required String password,
    required String role,
  }) async {
    try {
      final uc = await _auth.createUserWithEmailAndPassword(
          email: email, password: password);
      final uid = uc.user?.uid;
      if (uid == null) return {'success': false};
      await uc.user?.updateDisplayName(displayName);
      final status = 'active';
      final docData = {
        'displayName': displayName,
        'email': email,
        'phone': null,
        'role': role,
        'status': status,
        'provider': 'password',
        'createdAt': FieldValue.serverTimestamp(),
      };
      await _firestore.collection('users').doc(uid).set(docData);
      return {'success': true, 'uid': uid, 'role': role, 'status': status};
    } on FirebaseAuthException catch (e) {
      return {'success': false, 'error': e.code};
    } catch (e) {
      return {'success': false, 'error': e.toString()};
    }
  }

  // ------------------ Phone verification ------------------
  static Future<Map<String, dynamic>> sendPhoneVerification({
    required String phone,
  }) async {
    final q = await _firestore
        .collection('users')
        .where('phone', isEqualTo: phone)
        .limit(1)
        .get();
    final isNew = q.docs.isEmpty;
    final completer = Completer<Map<String, dynamic>>();

    await _auth.verifyPhoneNumber(
      phoneNumber: phone,
      timeout: const Duration(seconds: 60),
      verificationCompleted: (PhoneAuthCredential credential) async {
        try {
          final userCredential = await _auth.signInWithCredential(credential);
          final uid = userCredential.user?.uid;
          if (!completer.isCompleted) {
            completer.complete({
              'verificationId': '',
              'auto': true,
              'uid': uid,
              'newUser': isNew
            });
          }
        } catch (e) {
          if (!completer.isCompleted) completer.completeError(e);
        }
      },
      verificationFailed: (FirebaseAuthException e) {
        if (!completer.isCompleted) completer.completeError(e);
      },
      codeSent: (String verificationId, int? resendToken) {
        if (!completer.isCompleted) {
          completer.complete({
            'verificationId': verificationId,
            'auto': false,
            'newUser': isNew
          });
        }
      },
      codeAutoRetrievalTimeout: (String verificationId) {},
    );

    return completer.future;
  }

  static Future<VerifyResult> verifyPhoneOtp({
    required String verificationId,
    required String smsCode,
  }) async {
    try {
      final credential = PhoneAuthProvider.credential(
          verificationId: verificationId, smsCode: smsCode);
      final userCredential = await _auth.signInWithCredential(credential);
      final uid = userCredential.user?.uid;
      final isNew = userCredential.additionalUserInfo?.isNewUser ?? false;
      return VerifyResult(success: true, newUser: isNew, uid: uid);
    } on FirebaseAuthException {
      return VerifyResult(success: false, newUser: false, uid: null);
    } catch (e) {
      return VerifyResult(success: false, newUser: false, uid: null);
    }
  }

  // ------------------ Google sign-in ------------------
  static Future<GoogleSignInResult> signInWithGoogle() async {
    try {
      final googleUser = await _googleSignIn.signIn();
      if (googleUser == null) {
        return GoogleSignInResult(
            newUser: false, uid: null, displayName: null);
      }
      final googleAuth = await googleUser.authentication;
      final credential = GoogleAuthProvider.credential(
          accessToken: googleAuth.accessToken, idToken: googleAuth.idToken);
      final userCredential = await _auth.signInWithCredential(credential);
      final uid = userCredential.user?.uid;
      final isNew = userCredential.additionalUserInfo?.isNewUser ?? false;
      final displayName = userCredential.user?.displayName;
      return GoogleSignInResult(
          newUser: isNew, uid: uid, displayName: displayName);
    } catch (e) {
      rethrow;
    }
  }

  // ------------------ Complete signup ------------------
  static Future<bool> completeSignup({
    required String uid,
    required String displayName,
    required String role,
    String? email,
    String? phone,
    String provider = 'unknown',
  }) async {
    try {
      final status = 'active';
      final docData = {
        'displayName': displayName,
        'email': email,
        'phone': phone,
        'role': role,
        'status': status,
        'provider': provider,
        'createdAt': FieldValue.serverTimestamp(),
      };
      await _firestore
          .collection('users')
          .doc(uid)
          .set(docData, SetOptions(merge: true));
      final user = _auth.currentUser;
      if (user != null &&
          (user.displayName == null || user.displayName!.isEmpty)) {
        await user.updateDisplayName(displayName);
      }
      return true;
    } catch (e) {
      print('completeSignup error: $e');
      return false;
    }
  }

  // ------------------ Sign out ------------------
  static Future<void> signOut() async {
    try {
      await _auth.signOut();
      await _googleSignIn.signOut();
    } catch (_) {}
  }
}


 */
/*
// lib/services/auth_service.dart
import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';

class CheckResult {
  final bool exists;
  final List<String> providers;
  final String status;
  CheckResult({required this.exists, this.providers = const <String>[], this.status = 'none'});
}

class GoogleSignInResult {
  final bool newUser;
  final String? uid;
  final String? displayName;
  GoogleSignInResult({required this.newUser, this.uid, this.displayName});
}

class VerifyResult {
  final bool success;
  final bool newUser;
  final String? uid;
  VerifyResult({required this.success, required this.newUser, this.uid});
}

class AuthService {
  static final FirebaseAuth _auth = FirebaseAuth.instance;
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static final GoogleSignIn _googleSignIn = GoogleSignIn();



  // ------------------ Helpers ------------------

  static Future<String?> getUserRole(String uid) async {
    try {
      final doc = await _firestore.collection('users').doc(uid).get();
      if (doc.exists) {
        final data = doc.data();
        return data?['role'] as String?;
      }
    } catch (e) {
      print('getUserRole error: $e');
    }
    return null;
  }

  // ------------------ Identifier check ------------------

  static Future<CheckResult> checkIdentifier({
    required String method,
    required String identifier,
  }) async {
    try {
      if (method == 'email') {
        // 🔹 1️⃣ Check Firestore first
        final q = await _firestore
            .collection('users')
            .where('email', isEqualTo: identifier)
            .limit(1)
            .get();

        if (q.docs.isNotEmpty) {
          final data = q.docs.first.data();
          final provider = (data['provider'] ?? 'password') as String;
          final status = data['status'] ?? 'active';
          return CheckResult(
              exists: true, providers: [provider], status: status);
        }

        // 🔹 2️⃣ Try Firebase Auth via sign-in attempt
        try {
          await _auth.signInWithEmailAndPassword(
              email: identifier, password: 'invalid-temp-password');
        } on FirebaseAuthException catch (e) {
          if (e.code == 'wrong-password' ||
              e.code == 'user-disabled' ||
              e.code == 'too-many-requests') {
            // ✅ Email exists
            return CheckResult(exists: true, providers: ['password'], status: 'active');
          } else if (e.code == 'user-not-found') {
            // 🚫 Email doesn't exist
            return CheckResult(exists: false);
          }
        } catch (_) {}

        return CheckResult(exists: false);
      } else if (method == 'phone') {
        final q = await _firestore
            .collection('users')
            .where('phone', isEqualTo: identifier)
            .limit(1)
            .get();
        if (q.docs.isNotEmpty) {
          final data = q.docs.first.data();
          return CheckResult(
              exists: true,
              providers: [data['provider'] ?? 'phone'],
              status: data['status'] ?? 'active');
        }
        return CheckResult(exists: false);
      }
      return CheckResult(exists: false);
    } catch (e) {
      print('checkIdentifier error: $e');
      return CheckResult(exists: false);
    }
  }




  // ------------------ Email Sign-In / Sign-Up ------------------

  static Future<Map<String, dynamic>> signInWithEmail({
    required String email,
    required String password,
  }) async {
    try {
      final uc = await _auth.signInWithEmailAndPassword(
          email: email, password: password);
      final uid = uc.user?.uid;
      if (uid == null) return {'success': false, 'error': 'no-uid'};
      final doc = await _firestore.collection('users').doc(uid).get();
      if (!doc.exists)
        return {'success': true, 'uid': uid, 'newProfile': true};
      final data = doc.data()!;
      return {
        'success': true,
        'uid': uid,
        'role': data['role'],
        'status': data['status'] ?? 'active'
      };
    } on FirebaseAuthException catch (e) {
      return {'success': false, 'error': e.code};
    } catch (e) {
      return {'success': false, 'error': e.toString()};
    }
  }

  static Future<Map<String, dynamic>> signUpWithEmail({
    required String displayName,
    required String email,
    required String password,
    required String role,
  }) async {
    try {
      final uc = await _auth.createUserWithEmailAndPassword(
          email: email, password: password);
      final uid = uc.user?.uid;
      if (uid == null) return {'success': false};
      await uc.user?.updateDisplayName(displayName);
      await _firestore.collection('users').doc(uid).set({
        'displayName': displayName,
        'email': email,
        'role': role,
        'status': 'active',
        'provider': 'password',
        'createdAt': FieldValue.serverTimestamp(),
      });
      return {'success': true, 'uid': uid, 'role': role};
    } catch (e) {
      return {'success': false, 'error': e.toString()};
    }
  }

  // ------------------ Phone Auth ------------------

  static Future<Map<String, dynamic>> sendPhoneVerification({
    required String phone,
  }) async {
    final q = await _firestore
        .collection('users')
        .where('phone', isEqualTo: phone)
        .limit(1)
        .get();
    final isNew = q.docs.isEmpty;
    final completer = Completer<Map<String, dynamic>>();

    await _auth.verifyPhoneNumber(
      phoneNumber: phone,
      timeout: const Duration(seconds: 60),
      verificationCompleted: (cred) async {
        final userCred = await _auth.signInWithCredential(cred);
        final uid = userCred.user?.uid;
        completer.complete(
            {'verificationId': '', 'auto': true, 'uid': uid, 'newUser': isNew});
      },
      verificationFailed: (e) => completer.completeError(e),
      codeSent: (id, token) =>
          completer.complete({'verificationId': id, 'auto': false, 'newUser': isNew}),
      codeAutoRetrievalTimeout: (_) {},
    );

    return completer.future;
  }

  static Future<VerifyResult> verifyPhoneOtp({
    required String verificationId,
    required String smsCode,
  }) async {
    try {
      final cred =
      PhoneAuthProvider.credential(verificationId: verificationId, smsCode: smsCode);
      final userCred = await _auth.signInWithCredential(cred);
      final uid = userCred.user?.uid;
      final newUser = userCred.additionalUserInfo?.isNewUser ?? false;
      return VerifyResult(success: true, newUser: newUser, uid: uid);
    } catch (e) {
      return VerifyResult(success: false, newUser: false, uid: null);
    }
  }



  // ------------------ Google Sign-In ------------------

  static Future<GoogleSignInResult> signInWithGoogle() async {
    try {
      final googleUser = await _googleSignIn.signIn();
      if (googleUser == null) return GoogleSignInResult(newUser: false);
      final googleAuth = await googleUser.authentication;
      final cred = GoogleAuthProvider.credential(
        idToken: googleAuth.idToken,
        accessToken: googleAuth.accessToken,
      );
      final userCred = await _auth.signInWithCredential(cred);
      final uid = userCred.user?.uid;
      final newUser = userCred.additionalUserInfo?.isNewUser ?? false;
      final name = userCred.user?.displayName;
      return GoogleSignInResult(
          newUser: newUser, uid: uid, displayName: name);
    } catch (e) {
      print('Google SignIn error: $e');
      return GoogleSignInResult(newUser: false);
    }
  }

  // ------------------ Complete Signup ------------------

  static Future<bool> completeSignup({
    required String uid,
    required String displayName,
    required String role,
    String? email,
    String? phone,
    String provider = 'unknown',
  }) async {
    try {
      await _firestore.collection('users').doc(uid).set({
        'displayName': displayName,
        'email': email,
        'phone': phone,
        'role': role,
        'status': 'active',
        'provider': provider,
        'createdAt': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));
      final user = _auth.currentUser;
      if (user != null &&
          (user.displayName == null || user.displayName!.isEmpty)) {
        await user.updateDisplayName(displayName);
      }
      return true;
    } catch (e) {
      print('completeSignup error: $e');
      return false;
    }
  }

  // ------------------ Sign out ------------------

  static Future<void> signOut() async {
    try {
      await _googleSignIn.signOut();
      await _auth.signOut();
    } catch (_) {}
  }
}

 */
import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';

// ---------- Helper Models ----------

class CheckResult {
  final bool exists;
  final List<String> providers;
  final String status;
  CheckResult({
    required this.exists,
    this.providers = const <String>[],
    this.status = 'none',
  });
}

class GoogleSignInResult {
  final bool newUser;
  final String? uid;
  final String? displayName;
  GoogleSignInResult({required this.newUser, this.uid, this.displayName});
}

class VerifyResult {
  final bool success;
  final bool newUser;
  final String? uid;
  VerifyResult({required this.success, required this.newUser, this.uid});
}

// ---------- Auth Service ----------

class AuthService {
  static final FirebaseAuth _auth = FirebaseAuth.instance;
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static final GoogleSignIn _googleSignIn = GoogleSignIn();

  // ------------------ Get User Role ------------------
  static Future<String?> getUserRole(String uid) async {
    try {
      final doc = await _firestore.collection('users').doc(uid).get();
      if (doc.exists) {
        final data = doc.data();
        return data?['role'] as String?;
      }
    } catch (e) {
      print('getUserRole error: $e');
    }
    return null;
  }

  // ------------------ Identifier Check ------------------
  static Future<CheckResult> checkIdentifier({
    required String method,
    required String identifier,
  }) async {
    try {
      if (method == 'email') {
        // 1️⃣ Check Firestore first
        final q = await _firestore
            .collection('users')
            .where('email', isEqualTo: identifier)
            .limit(1)
            .get();

        if (q.docs.isNotEmpty) {
          final data = q.docs.first.data();
          final provider = (data['provider'] ?? 'password') as String;
          final status = data['status'] ?? 'active';
          return CheckResult(
            exists: true,
            providers: [provider],
            status: status,
          );
        }

        // 2️⃣ Try Firebase Auth
        try {
          await _auth.signInWithEmailAndPassword(
              email: identifier, password: 'invalid-temp-password');
        } on FirebaseAuthException catch (e) {
          if (e.code == 'wrong-password' ||
              e.code == 'user-disabled' ||
              e.code == 'too-many-requests') {
            return CheckResult(exists: true, providers: ['password'], status: 'active');
          } else if (e.code == 'user-not-found') {
            return CheckResult(exists: false);
          }
        }

        return CheckResult(exists: false);
      } else if (method == 'phone') {
        final q = await _firestore
            .collection('users')
            .where('phone', isEqualTo: identifier)
            .limit(1)
            .get();
        if (q.docs.isNotEmpty) {
          final data = q.docs.first.data();
          return CheckResult(
            exists: true,
            providers: [data['provider'] ?? 'phone'],
            status: data['status'] ?? 'active',
          );
        }
        return CheckResult(exists: false);
      }

      return CheckResult(exists: false);
    } catch (e) {
      print('checkIdentifier error: $e');
      return CheckResult(exists: false);
    }
  }

  // ------------------ Email Sign-In / Sign-Up ------------------

  static Future<Map<String, dynamic>> signInWithEmail({
    required String email,
    required String password,
  }) async {
    try {
      final uc = await _auth.signInWithEmailAndPassword(
          email: email, password: password);
      final uid = uc.user?.uid;
      if (uid == null) return {'success': false, 'error': 'no-uid'};

      final doc = await _firestore.collection('users').doc(uid).get();
      if (!doc.exists) return {'success': true, 'uid': uid, 'newProfile': true};

      final data = doc.data()!;
      return {
        'success': true,
        'uid': uid,
        'role': data['role'],
        'status': data['status'] ?? 'active',
      };
    } on FirebaseAuthException catch (e) {
      return {'success': false, 'error': e.code};
    } catch (e) {
      return {'success': false, 'error': e.toString()};
    }
  }

  static Future<Map<String, dynamic>> signUpWithEmail({
    required String displayName,
    required String email,
    required String password,
    required String role,
  }) async {
    try {
      final uc = await _auth.createUserWithEmailAndPassword(
          email: email, password: password);
      final uid = uc.user?.uid;
      if (uid == null) return {'success': false};

      await uc.user?.updateDisplayName(displayName);
      await _firestore.collection('users').doc(uid).set({
        'displayName': displayName,
        'email': email,
        'role': role,
        'status': 'active',
        'provider': 'password',
        'createdAt': FieldValue.serverTimestamp(),
      });

      return {'success': true, 'uid': uid, 'role': role};
    } catch (e) {
      return {'success': false, 'error': e.toString()};
    }
  }

  // ------------------ Phone Authentication ------------------

  static Future<Map<String, dynamic>> sendPhoneVerification({
    required String phone,
  }) async {
    final q = await _firestore
        .collection('users')
        .where('phone', isEqualTo: phone)
        .limit(1)
        .get();
    final isNew = q.docs.isEmpty;
    final completer = Completer<Map<String, dynamic>>();

    await _auth.verifyPhoneNumber(
      phoneNumber: phone,
      timeout: const Duration(seconds: 60),
      verificationCompleted: (cred) async {
        try {
          final userCred = await _auth.signInWithCredential(cred);
          final uid = userCred.user?.uid;
          completer.complete({
            'verificationId': '',
            'auto': true,
            'uid': uid,
            'newUser': isNew,
          });
        } catch (e) {
          completer.completeError(e);
        }
      },
      verificationFailed: (e) {
        completer.completeError(e);
      },
      codeSent: (id, token) {
        completer.complete({
          'verificationId': id,
          'auto': false,
          'newUser': isNew,
        });
      },
      codeAutoRetrievalTimeout: (_) {},
    );

    return completer.future;
  }

  // ✅ Added / Fixed verifyPhoneOtp definition
  static Future<VerifyResult> verifyPhoneOtp({
    required String verificationId,
    required String smsCode,
  }) async {
    try {
      final cred = PhoneAuthProvider.credential(
          verificationId: verificationId, smsCode: smsCode);
      final userCred = await _auth.signInWithCredential(cred);
      final uid = userCred.user?.uid;
      final newUser = userCred.additionalUserInfo?.isNewUser ?? false;
      return VerifyResult(success: true, newUser: newUser, uid: uid);
    } catch (e) {
      print('verifyPhoneOtp error: $e');
      return VerifyResult(success: false, newUser: false, uid: null);
    }
  }

  // ------------------ Google Sign-In ------------------

  static Future<GoogleSignInResult> signInWithGoogle() async {
    try {
      final googleUser = await _googleSignIn.signIn();
      if (googleUser == null) return GoogleSignInResult(newUser: false);

      final googleAuth = await googleUser.authentication;
      final cred = GoogleAuthProvider.credential(
        idToken: googleAuth.idToken,
        accessToken: googleAuth.accessToken,
      );

      final userCred = await _auth.signInWithCredential(cred);
      final uid = userCred.user?.uid;
      final newUser = userCred.additionalUserInfo?.isNewUser ?? false;
      final name = userCred.user?.displayName;

      return GoogleSignInResult(newUser: newUser, uid: uid, displayName: name);
    } catch (e) {
      print('Google SignIn error: $e');
      return GoogleSignInResult(newUser: false);
    }
  }

  // ------------------ Complete Signup ------------------

  static Future<bool> completeSignup({
    required String uid,
    required String displayName,
    required String role,
    String? email,
    String? phone,
    String provider = 'unknown',
  }) async {
    try {
      await _firestore.collection('users').doc(uid).set({
        'displayName': displayName,
        'email': email,
        'phone': phone,
        'role': role,
        'status': 'active',
        'provider': provider,
        'createdAt': FieldValue.serverTimestamp(),
      }, SetOptions(merge: true));

      final user = _auth.currentUser;
      if (user != null &&
          (user.displayName == null || user.displayName!.isEmpty)) {
        await user.updateDisplayName(displayName);
      }

      return true;
    } catch (e) {
      print('completeSignup error: $e');
      return false;
    }
  }

  // ------------------ Sign out ------------------

  static Future<void> signOut() async {
    try {
      await _googleSignIn.signOut();
      await _auth.signOut();
    } catch (_) {}
  }
}

